/**
* RPG Stat Manager Central Server
* This is the server for the data accass of the RPG Users
*
* OpenAPI spec version: 1.0.0
* Contact: holloszaboakos.1996@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.example.rpgstatmanager.swagger.client.models


/**
 * 
 * @param id 
 * @param character_id 
 * @param race_id 
 * @param name 
 * @param positive 
 * @param description
 * @param effect 
 */
data class Ability (
    val id: String? = null,
    val character_id: String? = null,
    val race_id: String? = null,
    val name: String? = null,
    val positive: Boolean? = null,
    val description: String? = null,
    val effect: String? = null
) {

}

