/**
* RPG Stat Manager Central Server
* This is the server for the data accass of the RPG Users
*
* OpenAPI spec version: 1.0.0
* Contact: holloszaboakos.1996@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.example.rpgstatmanager.swagger.client.models


/**
 * 
 * @param id 
 * @param character_id 
 * @param half 
 * @param line 
 * @param stat1 
 * @param stat2 
 * @param value 
 */
data class MoveType (
    val id: String? = null,
    val character_id: String? = null,
    val half: String? = null,
    val line: String? = null,
    val stat1: String? = null,
    val stat2: String? = null,
    val value: Long? = null
) {

}

