/**
* RPG Stat Manager Central Server
* This is the server for the data accass of the RPG Users
*
* OpenAPI spec version: 1.0.0
* Contact: holloszaboakos.1996@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.example.rpgstatmanager.swagger.client.models


/**
 * 
 * @param id 
 * @param character_id 
 * @param move_type_id 
 * @param cardRestriction 
 * @param description
 * @param effect 
 */
data class Move (
    val id: String? = null,
    val character_id: String? = null,
    val move_type_id: String? = null,
    val cardRestriction: String? = null,
    val description: String? = null,
    val effect: String? = null
) {

}

