/**
* RPG Stat Manager Central Server
* This is the server for the data accass of the RPG Users
*
* OpenAPI spec version: 1.0.0
* Contact: holloszaboakos.1996@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.example.rpgstatmanager.swagger.client.models


/**
 * 
 * @param id 
 * @param introvert 
 * @param extrovert 
 * @param observant 
 * @param intuitive 
 * @param thinking 
 * @param feeling 
 * @param judging 
 * @param prospecting 
 * @param assertive 
 * @param turbulent 
 */
data class PersonalityType (
    val id: kotlin.String? = null,
    val introvert: kotlin.Long? = null,
    val extrovert: kotlin.Long? = null,
    val observant: kotlin.Long? = null,
    val intuitive: kotlin.Long? = null,
    val thinking: kotlin.Long? = null,
    val feeling: kotlin.Long? = null,
    val judging: kotlin.Long? = null,
    val prospecting: kotlin.Long? = null,
    val assertive: kotlin.Long? = null,
    val turbulent: kotlin.Long? = null
) {

}

