/**
* RPG Stat Manager Central Server
* This is the server for the data accass of the RPG Users
*
* OpenAPI spec version: 1.0.0
* Contact: holloszaboakos.1996@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.example.rpgstatmanager.swagger.client.models


/**
 * 
 * @param id 
 * @param character_id 
 * @param introvert 
 * @param extrovert 
 * @param observent
 * @param intuitive 
 * @param thinking 
 * @param feeling 
 * @param judging 
 * @param prospecting 
 * @param assertive 
 * @param turbulent 
 */
data class PersonalityType (
    val id: String? = null,
    val character_id: String? = null,
    val introvert: Long? = null,
    val extrovert: Long? = null,
    val observent: Long? = null,
    val intuitive: Long? = null,
    val thinking: Long? = null,
    val feeling: Long? = null,
    val judging: Long? = null,
    val prospecting: Long? = null,
    val assertive: Long? = null,
    val turbulent: Long? = null
) {

}

