/**
* RPG Stat Manager Central Server
* This is the server for the data accass of the RPG Users
*
* OpenAPI spec version: 1.0.0
* Contact: holloszaboakos.1996@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.example.rpgstatmanager.swagger.client.models


/**
 * 
 * @param id 
 * @param categoryName 
 * @param familyName 
 * @param raceName 
 * @param subraceName 
 */
data class Race (
    val id: kotlin.String? = null,
    val categoryName: kotlin.String? = null,
    val familyName: kotlin.String? = null,
    val raceName: kotlin.String? = null,
    val subraceName: kotlin.String? = null
) {

}

